### ISSUE TITLE
Passing int(LineEdit.text())

### ISSUE THREAD

**Issue by nickandwolf** [ceccopierangiolieugenio/pyTermTk#105]
Ran into an issue trying to set a SpinBox's value with a LineEdit.
using v._text works though
strange because your code for [LineEdit](https://github.com/ceccopierangiolieugenio/pyTermTk/blob/main/TermTk/TTkWidgets/lineedit.py#L76) has:
```
def text(self):
        '''text'''
        return self._text
```

Here's my thing:
```
#HumanityChanged is called by a LineEdit
#currentEmp and emp are SpinBoxes
#GetCurrentEMP returns an integer after doing hokey math on the arguments
def HumanityChanged(self, v=-1):
    self.currentEmp.setValue(self.character.GetCurrentEMP(int(v.text()), self.emp.value()))
    #AttributeError: 'TTkString' object has no attribute 'text'
```

**Comment by ceccopierangiolieugenio** [comment]
Sorry, forgot to reply early
I just push the version **0.20.0a2** where you can use "int()" with a TTkString

anyway, from your example I think you are using the **textChanged** or **textEdited** signal
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/main/TermTk/TTkWidgets/lineedit.py#L50-L51

those signals return a TTKString
and you don't need to use the **text()** method to process them

you can just:
```python
def HumanityChanged(self, v=-1):
    self.currentEmp.setValue(self.character.GetCurrentEMP(int(v), self.emp.value()))
    #AttributeError: 'TTkString' object has no attribute 'text'
```

**Comment by ceccopierangiolieugenio** [comment]
Added an example here:
https://gist.github.com/ceccopierangiolieugenio/ac345be1b9fbabc07109e70982d2543b

[tryItOnline](https://ceccopierangiolieugenio.github.io/pyTermTk/sandbox/sandbox.html?fileUri=https://gist.githubusercontent.com/ceccopierangiolieugenio/ac345be1b9fbabc07109e70982d2543b/raw/28f5a5d0c0403c8237b88775776576fe0720b3c4/issue_105_passing_lineEdit_value.py)
