### ISSUE TITLE
Change TTkCheckbox checked status

### ISSUE THREAD

**Issue by nickandwolf** [ceccopierangiolieugenio/pyTermTk#106]
So there's a strange imbalance between bool and int values for Checkbox states.
I was trying to use bool to .setCheckState() and .setChecked() however only when I switched to using 0 and 2 (ignoring the half-state of 1) did I find some success.

**Comment by ceccopierangiolieugenio** [comment]
[setChecked](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.checkbox.html#TermTk.TTkWidgets.checkbox.TTkCheckbox.setChecked) - [isChecked](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.checkbox.html#TermTk.TTkWidgets.checkbox.TTkCheckbox.isChecked) is an easy way to use the checkbox with booleans.
(I recently introduced it once I noticed its usage in the QT)
but I just noticed that the [documentation](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.checkbox.html#TermTk.TTkWidgets.checkbox.TTkCheckbox.setChecked) for some reason was not correctly generated and the bool status is missing.
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/5626955393f492cddb568cbe7a5fa150f4acc5e5/TermTk/TTkWidgets/checkbox.py#L135-L139
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/5626955393f492cddb568cbe7a5fa150f4acc5e5/TermTk/TTkWidgets/checkbox.py#L142-L147

[setCheckState](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.checkbox.html#TermTk.TTkWidgets.checkbox.TTkCheckbox.setCheckState) - [checkState](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.checkbox.html#TermTk.TTkWidgets.checkbox.TTkCheckbox.checkState) should be used to handle the different checking states.
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/5626955393f492cddb568cbe7a5fa150f4acc5e5/TermTk/TTkWidgets/checkbox.py#L150-L154
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/5626955393f492cddb568cbe7a5fa150f4acc5e5/TermTk/TTkWidgets/checkbox.py#L157-L162
