### ISSUE TITLE
Right way to quit app

### ISSUE THREAD

**Issue by mars1211** [ceccopierangiolieugenio/pyTermTk#111]
Good day. 
I am trying to exit the application using the TTkHelper.quit() command - the program closes, but after that the pressed buttons are not displayed in the console.
This is bug or exist right way to do that?

**Comment by ceccopierangiolieugenio** [comment]
**TTkHelper.quit()** should release all the widgets,
quit the program and bring the controls back to the shell.
I am not sure about what you are experiencing, after this call you just got a black screen without shell prompt?
Do you have a code example that highlight this issue?

**Comment by ceccopierangiolieugenio** [comment]
which terminal are you using?
Is it running over the serial?
