### ISSUE TITLE
Very Strange issue after upgrading into last version...(TypeError: unsupported format string passed to TTkString.__format__)

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#131]
Hi
My program was working fine, but then I decided to upgrade to your last version (to try also ttlDesigner) but suddenly my program started to crash on strange lines that I can't see what is the issue:
for example this error:

```
  File "/home/larry/IdeaProjects/investigations/lab-constructor/./lab-constructor.py", line 1250, in <lambda>
    generate.clicked.connect(lambda: self.tui_setup_generate_nodes(node_frame, group_name))
  File "/home/larry/IdeaProjects/investigations/lab-constructor/./lab-constructor.py", line 1355, in tui_setup_generate_nodes
    node_ports += f"{node_setup[each_setup]:<{headers_size[hs]}} "
TypeError: unsupported format string passed to TTkString.__format__
```

What I don't get it is it says `TypeError: unsupported format string passed to TTkString.__format__` but line where this happens I'm not using that property (yet):

```
                node_ports = ""

                for hs, each_setup in enumerate(node_setup):
                    node_setup[each_setup] = LabInfra.validate_port(node_setup[each_setup])
                    node_ports += f"{node_setup[each_setup]:<{headers_size[hs]}} "        # --> This is line 1355
                    node.set(each_setup, node_setup[each_setup])
                    # node_ports.append(ttk.TTkLabel(text=node_setup[each_setup]))
```

I'm still going around the program to see why this error is happening. What I'm doing here is generate a concatenated string with some information

I got another error too in a different part of this program. But will concentrate on this one first.

**Comment by castben** [comment]
All right, I think I will do a deper investigation on my side, 

I think you changed methods, I need to check how I'm getting values from each component it seems this has been changed, I've attached a debugger and I can see why now this is happening:
```
>>> node_setup
{'P2P-PORT': <TermTk.TTkCore.string.TTkString object at 0x7f8124306390>, 'NODE_RPC_ADDRESS': <TermTk.TTkCore.string.TTkString object at 0x7f8124305a30>, 'NODE_ADMIN_ADDRESS': <TermTk.TTkCore.string.TTkString object at 0x7f81243056c0>}
>>> headers_size
[10, 25, 25, 10, 10, 10, 10]
```
I'm not expecting to have the actual object here just its vaules (which are strings) so please disregard this issue, I need to check how I'm getting values here to correct this issue.

I think you can disregard this

**Comment by castben** [comment]
Ok now I got it, you are now returning a TTKString from TTKLineEdit widget, I'm sure before was a plain String type :D no worries, I will take care of this I will close this issue as is not in your side :-) 

Thankfully I just need to change it on this method, as all other places where I claim widget values will call this method

Will close this one.

**Comment by ceccopierangiolieugenio** [comment]
Sorry for this issue, and my late reply,
when I was developing ttkDesigner I realised many design issues I have to face sooner or later and this will break compatibility with some old code.
In one of the next releases I have to change also the way the layouts are handled but this should not impact any code that does not take advantages of some internals (I hope so)
