### ISSUE TITLE
Failing to Set a value to a TTkLineEdit widget after initialised  using metod `setText`...

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#132]
Hi hope you are doing well, I've been trying to setup proper values to a TTkLineEdit widget after being initialised using following:

``` 
fiedl = ttk.TTkLineEdit()
....
....
...
field.setText = "New Text"

```
But this doesn't work, I've tried several ways without success... then I remembered error I got before where this component return a TTkString type instead of string, so I went to your `.setText` method and found this:

```
    @pyTTkSlot(str)
    def setText(self, text, cursorPos=0x1000):
        '''setText'''
        if text != self._text:
            self.textChanged.emit(text)
            self._text = TTkString(text)
            self._cursorPos = max(0,min(cursorPos, len(text)))
            self._pushCursor()
```

Then I tried this:
```
field._text = TTkString("New Text") 
```
and it worked.... could this be a bug? or what I'm doing wrong?

**Comment by ceccopierangiolieugenio** [comment]
Hi, ufortunately I am in the process of removing all the property fields:
(i.e.) in [0.20.0-a](https://github.com/ceccopierangiolieugenio/pyTermTk/releases/tag/0.20.0-a) I removed the **text** property from the **TTkLabel** in https://github.com/ceccopierangiolieugenio/pyTermTk/commit/599aa9144fe116e4abe4ac80505fb3aea0ac3725

About LineEdit I don't remember ever using the properties,
instead there are 2 methods you shoud use;

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/ac3a7713b06a45912c88ca9ca841de5e5819f046/TermTk/TTkWidgets/lineedit.py#L67-L74

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/ac3a7713b06a45912c88ca9ca841de5e5819f046/TermTk/TTkWidgets/lineedit.py#L76-L78



In your example it should be:
```python
fiedl = ttk.TTkLineEdit()
....
....
...
field.setText("New Text")
```
or
```python
field.setText(TTkString("New Text")) 
```
