### ISSUE TITLE
Demo doesn't run

### ISSUE THREAD

**Issue by cherbert** [ceccopierangiolieugenio/pyTermTk#144]
python3 demo/demo.py -f

Traceback (most recent call last):
  File "/home/cherbert/pf/pyTermTk/demo/demo.py", line 279, in <module>
    main()
  File "/home/cherbert/pf/pyTermTk/demo/demo.py", line 274, in main
    demoShowcase(winTabbed1, border)
  File "/home/cherbert/pf/pyTermTk/demo/demo.py", line 169, in demoShowcase
    tabMenuBar.addTab(demoMenuBar(),     " MenuBar Test ")
  File "/home/cherbert/pf/pyTermTk/demo/showcase/menubar.py", line 36, in demoMenuBar
    fileMenu = frameTop.newMenubarTop().addMenu("&File")
AttributeError: 'TTkFrame' object has no attribute 'newMenubarTop'. Did you mean: '_menubarTop'?

**Comment by ceccopierangiolieugenio** [comment]
In the past few weeks I am reworking most of the code to keep it uniform among all the widgets
anyway this issue should have already been fixed in

https://github.com/ceccopierangiolieugenio/pyTermTk/commit/b0bb367f81a4d43fdda4ec71b25adad8e5482012#diff-bd7107eb47ebecb5753c8c391712e9fed8fec6709baaa9c18cdee5fceb50cd93R36

try to pull the more recent code.

**Comment by cherbert** [comment]
I don't understand. That commit is on main branch. I followed the instructions and did
git clone https://github.com/ceccopierangiolieugenio/pyTermTk.git

Should that not give me the latest?

**Comment by cherbert** [comment]
I have just checked and I have the latest commit. That is where the error is coming from. You can see that in the error I posted.

**Comment by ceccopierangiolieugenio** [comment]
I think you have pyTermTk installed using pip
and the demo is using that version that does not include the more recent changes
instead of the library downloaded using git.

try to run:
```bash
PYTHONPATH=. demo/demo.py
```

**Comment by cherbert** [comment]
Doesn't work

**Comment by ceccopierangiolieugenio** [comment]
It seems that putty by default is not supporting those charset:
```
U+2596  ▖       e2 96 96        QUADRANT LOWER LEFT
U+2597  ▗       e2 96 97        QUADRANT LOWER RIGHT
U+2598  ▘       e2 96 98        QUADRANT UPPER LEFT
U+2599  ▙       e2 96 99        QUADRANT UPPER LEFT AND LOWER LEFT AND LOWER RIGHT
U+259A  ▚       e2 96 9a        QUADRANT UPPER LEFT AND LOWER RIGHT
U+259B  ▛       e2 96 9b        QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER LEFT
U+259C  ▜       e2 96 9c        QUADRANT UPPER LEFT AND UPPER RIGHT AND LOWER RIGHT
U+259D  ▝       e2 96 9d        QUADRANT UPPER RIGHT
U+259E  ▞       e2 96 9e        QUADRANT UPPER RIGHT AND LOWER LEFT
U+259F  ▟       e2 96 9f        QUADRANT UPPER RIGHT AND LOWER LEFT AND LOWER RIGHT
```

you can try to install those fonts and use them in  putty
https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/DejaVuSansMono.zip

![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/f7ec8a0a-d8f5-4f9e-9273-7cd2114a6022)

![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/92ec6cd8-48db-4a46-9fb2-f554016352d4)

**Comment by cherbert** [comment]
That worked just great. Thanks again.
