### ISSUE TITLE
Question: How can  assign 2 actions to a single CheckBox.stateChanged event?

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#145]
Hi,
I'm trying to "activate" textfield entries depending on a stateChanged from a checkbox. if state is true they should be visible, if state is false, they should be disabled or hidden.

This "forms" are being build programmatically. 
Here is bit of code that build this form, and create a "dependency" for fields that need to be hidden/disabled:

```python
        for each_node_rq in lab_requirement.get_additional_requirements(node_type):
            if each_node_rq in self.lab_user_setup:
                for each_setup in lab_requirement.get_additional_requirements(
                        node_type, each_node_rq, self.lab_user_setup[each_node_rq]):

                    label, default_setting = LabInfra.setup_required_settings(each_setup, defaults)
                    var_action = LabInfra.check_variable_rules(label)
                    if var_action:
                        if var_action['rule-action'] == 'hide':
                            var_action['widget'].stateChanged.connect(
                                lambda x: default_setting.setVisible(x == ttk.TTkK.Checked))
                    tui_node_form.add_widget(f"{label}", default_setting, group=group_name)
```
Actual code that "creates" this dependency is:
```python
                    if var_action:
                        if var_action['rule-action'] == 'hide':
                            var_action['widget'].stateChanged.connect(
                                lambda x: default_setting.setVisible(x == ttk.TTkK.Checked))
```
I know this may look bit complicated; this is in a for-loop which create a `form` on the fly(reading configurations setup) it looks like this:

![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/56597585/d57837f4-18bd-4d22-ba52-9272648e4485)

last 2 fields:
``` 
USER_RPC
PASSWORD_RPC
```
Will be enabled only if `ACTIVATE_RPC` is checked-on.
`var_action['widget']` contains actual checkbox widget
`default_setting` hold actual widget that will be disabled/hiden.

At the moment the code that generates this form is only "hiding" one of the fields when I uncheck  `ACTIVATE_RPC` so it looks like this:
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/56597585/fa35861b-66fd-40cf-b1b3-4d2b563fa5a8)

It is like is taking only last event (I mean second event overwrite first one that was created)

I know I can do this diferently, like put all widgets I want to hide in a function and then call that funtion... but this will mean I need to modify the actual code that creates this form on the fly.

If I can't assign more than one action to a single event, then I will approach using other method, but just wanted to ask you first if I'm doing it in wrong way.

Thank you a lot for your time! 

Regards,
Larry

**Comment by castben** [comment]
Thank you I will check this out now and will report back to you shortly!

**Comment by ceccopierangiolieugenio** [comment]
I just noticed that the clicked event return a bool as it is suposed to be used by the toggled event:

you can find the updated solution here

https://ceccopierangiolieugenio.github.io/pyTermTk/sandbox/sandbox.html?fileUri=https://gist.githubusercontent.com/ceccopierangiolieugenio/a46530db30cd728105046842f0011111/raw/3b2657e8c702deeb5ce0a20931a3b476e9bd7a7c/issue_145_loop_callbacks.py

so this should work as well;
```python
                            var_action['widget'].clicked.connect(default_setting.setVisible)
```
