### ISSUE TITLE
Hide/show or Enable/Disable a single Tab page from a Tab panel

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#147]
Hi,

I've a tab panel with few tabs on it, some of these tabs (at least 1 for now) will depends on selection on a previous tab, if user select Item 2 or 3 for example this tab will show up.

Anything else this tab should be hiden or disabled.

I've tried to use methods:
* tab_page.hide()
* tab_page.setVisible(False)
* tab_page.setEnabled(False)

But none of these methods hide(preferred) or disable tab I want, I tested these methods (like hide()) to  whole tab_panel, and it works, it hide the whole panel, but I can't manage to hide/show a single tab from tab_panel

**Comment by ceccopierangiolieugenio** [comment]
The api available for the tab widget are not super extensive.

Do you want a way to disable the tab completely so it cannot be selected?
and disable also the widget included in it?

**Comment by castben** [comment]
Hi ok not a problem I thought it was something I was doing wrong.

Yes on my program there're a select box where you can choose to use a Database, selecting "Postgres" or "Oracle" will make available this tab as it has more information about database version and docker setup... but also user can select `H2` which is a very compact DB that doens't need this extra tab.

Ok don't worry I will destroy/re-create this tab if it is needed, I just wanted to be sure I was not doing something wrong.
