### ISSUE TITLE
Trying to reset the text of label using the code

### ISSUE THREAD

**Issue by MohamedElgamal** [ceccopierangiolieugenio/pyTermTk#163]
Trying to reset the value of label after the user execute  certain action like clicking on button ( reset label)
I tried the following code and its not working 
<pre>
def clear_screen_input_fields(self, ref_item_list):
    for item in ref_item_list:
        item._text = ""
</pre>
the ref_item_list is an array that hold a reference to label object 
it doesn't work for me

**Comment by ceccopierangiolieugenio** [comment]
try to use **[setText()](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.label.html#TermTk.TTkWidgets.label.TTkLabel.setText)**
all the underscored variables are internals and should not be used.

```python
def clear_screen_input_fields(self, ref_item_list):
    for item in ref_item_list:
        item.setText("")
'''

**Comment by MohamedElgamal** [comment]
thanks it work for me , I have other question, I took a look on documentation on how to create a table but can't find an example of it can't figure out how to create tables, I want to create a table with 3 column and the row will be fetched from the database

**Comment by ceccopierangiolieugenio** [comment]
I still have not a fully functional table widget
you can either use the fancy table (the controls are limited)
or you can adapt a  tree widget to be basically a tree without leafs
everything depend on which features you need in the table.
the tree widget may be more customizable.

**Comment by MohamedElgamal** [comment]
i only need to display the data two user as following have three ( column : job id , script_path , state ) 
and have multiple rows i search in your repo and see FancyTable but can't figure out how to do it

**Comment by MohamedElgamal** [comment]
Thanks
