### ISSUE TITLE
`TTkConstant.Input_Number` does not allow `-` or `.`

### ISSUE THREAD

**Issue by russkel** [ceccopierangiolieugenio/pyTermTk#176]
When trying to use a `LineEdit` widget with `inputType` set to `TTkConstant.Input_Number`, the characters  `-` or `.` aren't permitted, which are used for negative numbers or decimals.

Perhaps another `inputType` could be added allowing for these?

**Comment by ceccopierangiolieugenio** [comment]
the character "-" is permitted if the cursor is at the beginning of the line.
I will check and fix the dot issue.

**Comment by ceccopierangiolieugenio** [comment]
The fix has been delivered in the version **0.34.0a**

**Comment by russkel** [comment]
What a quick turn around. Thanks a lot.
