### ISSUE TITLE
`TTkLineEdit` of 1 line height does not pass on up/down keys

### ISSUE THREAD

**Issue by russkel** [ceccopierangiolieugenio/pyTermTk#178]
I have a few checkboxes and then `TTkLineEdit` widgets in a form like arrangement, and once I navigate to the line edits using the down arrow key and get to the first LineEdit, I am no longer able to use up or down keys as they are captured by the LineEdit. I then have to use the `Tab` key.

Should this be the behavior for a single LineEdit? MultiLine is of course a different case.

**Comment by ceccopierangiolieugenio** [comment]
The line edit capture automatically all the arrow keys, but the up/down key are not strictly required/used.
I need to check if I can make an exception for them or at least make it configurable.

**Comment by ceccopierangiolieugenio** [comment]
I am still trying to think how to address this issue in the best way.
I don't want to add too many case specific api (i.e. a boolean to enable disable this just for the TextEdit).

I should allow some kind of key mapping that can be applied to some widgets.

I normally check the way qt handle those corner cases and in this situation it just capture the keyboard and does not allow any focus switch (same happen with other widgets)

A quick workaround can be to reimplement the LineEdit overriding the up and down keypresses.

```python
class MyLineEdit(ttk.TTkLineEdit):
    def keyEvent(self, evt):
        if (evt.type == ttk.TTkK.SpecialKey and
            evt.key in (ttk.TTkK.Key_Up,ttk.TTkK.Key_Down)):
             return False
        return super().keyEvent(evt)
```

You can find an example here:
https://gist.github.com/ceccopierangiolieugenio/19ab2a2e2be10b760091b648829aab79

[tryItOnline](https://ceccopierangiolieugenio.github.io/pyTermTk/sandbox/sandbox.html?fileUri=https://gist.githubusercontent.com/ceccopierangiolieugenio/19ab2a2e2be10b760091b648829aab79/raw/464cbfb59db5d27c476c20911dd72b716f0e359a/issue_178_UpDown_LineEdit_Focus.py)

**Comment by ceccopierangiolieugenio** [comment]
Anyway, LineEdit does not require those keys, I need to investigate if this may affect other widgets relying on it (combobox,spinbox).

**Comment by ceccopierangiolieugenio** [comment]
I delivwered a change in **0.34.0a7** that allows line edit to change the focus using up/down

**Comment by russkel** [comment]
This is great. I will give it a shot, thanks. Will be developing a few terminal applications for ROS2 tools, so I'll hopefully have some PRs for you as well.

**Comment by ceccopierangiolieugenio** [comment]
Thanks,
Let me know if you have some requests or ideas for improvements.
