### ISSUE TITLE
termTK Help

### ISSUE THREAD

**Issue by nevionix** [ceccopierangiolieugenio/pyTermTk#181]
Hi there,

I was hoping for some help - please note that I am very beginner, but my 2 questions should be easy for someone advanced:

1. Is there a way that I can start a frame/window immediately maximized? IE how can I start this window maximized?

ttk.TTkWindow(parent=None, border=True, size=(150,40), flags = ttk.TTkK.WindowFlag.WindowMaximizeButtonHint | ttk.TTkK.WindowFlag.WindowCloseButtonHint)

2. How can I make a button close only the frame/window that it is "attaced" to. IE my form/window asks input, but if cancel button is pressed, the form window should close.

Many thanks for any assistance.

Regards,

**Comment by ceccopierangiolieugenio** [comment]
Solution1:
You can retrieve the full terminal size
pros: it just works
cons: if the window is inside another widget it will be still maximized to the terminal size  so it will be bigger than the area available

```python
import TermTk as ttk

root = ttk.TTk()

# Get the terminal sizes
w,h = ttk.TTkTerm.getTerminalSize()
win = ttk.TTkWindow(parent=root, border=True, size=(w,h), flags = ttk.TTkK.WindowFlag.WindowMaximizeButtonHint | ttk.TTkK.WindowFlag.WindowCloseButtonHint)

# Create a button and connect with the window close action
btn = ttk.TTkButton(parent=win, text="Close", border=True)
btn.clicked.connect(win.close)

root.mainloop()
```

Solution2:
You can use a gridLayout
pros: it just works
cons: if the temrinal or the widget is resized the window is maximised again
```python
import TermTk as ttk

root = ttk.TTk(layout=ttk.TTkGridLayout())

# Get the terminal sizes
win = ttk.TTkWindow(parent=root, border=True, flags = ttk.TTkK.WindowFlag.WindowMaximizeButtonHint | ttk.TTkK.WindowFlag.WindowCloseButtonHint)

# Create a button and connect with the window close action
btn = ttk.TTkButton(parent=win, text="Close", border=True)
btn.clicked.connect(win.close)

root.mainloop()
```

Both solutions include the close button

**Comment by nevionix** [comment]
Thank you very very much :-D
