### ISSUE TITLE
TTkWindow/TTkFrame focus

### ISSUE THREAD

**Issue by nevionix** [ceccopierangiolieugenio/pyTermTk#185]
Hi,

Please can someone help me with the following? :

How can I make a termtk window or frame immediately take focus, or input focus? IE as soon as it's displayed the focus of input/active  must go to that frame/window?

Best regards,

**Comment by ceccopierangiolieugenio** [comment]
you can use the [setFocus()](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.widget.html#TermTk.TTkWidgets.widget.TTkWidget.setFocus) api

**Comment by nevionix** [comment]
Legend! Very much appreciated :-)
