### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by ecliipt** [ceccopierangiolieugenio/pyTermTk#190]
Hi i've been trying to mess around with the demo script and I was wondering if it was possible ti make a TTkTabWidget with some tabs that are not closable and some other tabs that are closable.
Another question I have is if it was possible to have the windows (like the pop up "sources" window that shows the sources) to not disappear when i click in another object.
I was not sure if i was supposed to ask these things here or not, so, sorry if this is the wrong place to put them.
Thanks!

**Comment by ceccopierangiolieugenio** [comment]
About the popup window that does not close you can have a look to the scratchpad windon in the ttkDesigner:

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/663cb032fd33ffd889c2ce1ce3b5731b0b109e3c/ttkDesigner/app/designer.py#L233-L240

Forcing "toolWindow=True" prevent the overlay window to be closed if unfocused

**Comment by ceccopierangiolieugenio** [comment]
About having at the same time closable and not closable tabs , it is a feature I haven't thought about.
I think I should add in the next, release one of the next days.
