### ISSUE TITLE
Question: TTkTextEdit: Understanding coloring/styles

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#195]
Hi, I'm trying to implement a coloring scheme for my TTkTextEdit widget, to highlight some specific words; I was having a look to your example at the tutorial page specifically this small part:

```python
def demoTextEdit(root=None, document=None):
    frame = ttk.TTkFrame(parent=root, border=False, layout=ttk.TTkGridLayout())

    # If no document is passed a default one is created,
    # In this showcase I want to be able to share the same
    # document among 2 textEdit widgets
    te = ttk.TTkTextEdit(document=document, lineNumber=True)

    te.setReadOnly(False)

    te.setText(ttk.TTkString("Text Edit DEMO\n",ttk.TTkColor.UNDERLINE+ttk.TTkColor.BOLD+ttk.TTkColor.ITALIC))

    # Load ANSI input
    if os.path.exists(os.path.join(os.path.dirname(os.path.abspath(__file__)),'textedit.ANSI.txt')):
        te.append(ttk.TTkString("ANSI Input Test\n",ttk.TTkColor.UNDERLINE+ttk.TTkColor.BOLD))
        with open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'textedit.ANSI.txt')) as f:
            te.append(f.read())
```

And I was wondering how do you change colors of text, only way i can think of, text has already coloring codes when you read it... as I can't see any specific line were you set colors to it.

So what I mean the file `textedit.ANSI.txt` has color codes already... 

but if I have a file that is plain text, only way I have to highlight words, is to read  line by line, and separate line into "words" then set colors to a specific word and re-build line and add it into textEdit widget...

similar to what you do here:
```python
    te.append(ttk.TTkString("Random TTkString Input Test\n",ttk.TTkColor.UNDERLINE+ttk.TTkColor.BOLD))
    te.append(ttk.TTkString('\n').join([ getUtfColoredSentence(3,10) for _ in range(50)]))
```

 but I think this will be very slow if file I'm loading is big (let's say couple of megs)...

Or is there a way I can pre-process this file adding specific "color" tags to file then load it at once?

**Comment by ceccopierangiolieugenio** [comment]
Sorry for the very late reply
Unfortunately at the moment there is not easy solution for this,
TTkTextEdit import automatically ansi color codes
i.e.:
here I use the ansi exporter of ppygments to colorize the sourcecode:

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/a64408b46ce99a29359c2285284697993f7e662e/tests/test.ui.018.TextEdit.Pygments.py#L46-L50

alternatively you can have a look at this routine I use to colorize the sorce viewer in the demo:

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/789a27215cd556f45f583274069ff419f7a4d3a1/demo/demo.py#L56-L88

you can also etry to extend the TextEdit adding a token parser
I can try to provide a demo for this

anyway, TTkString has a colorizer routine that can help you in this task:

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/789a27215cd556f45f583274069ff419f7a4d3a1/demo/demo.py#L59C28-L61

**Comment by castben** [comment]
Hi mate, not a problem I know you were busy on that, I saw your last post and looks great Windows stuff! good work.

I will take your advice on this thank you for your help. I have another questions if you don't mind I will open a new Issue for it as it is a separate question, but also related to ttkTimer ...

You can close this one now, thanks for your time

**Comment by castben** [comment]
I will go with your `stupidPythonHighlighter`   as it flexible to select what kind of words I want to highlight :D

**Comment by castben** [comment]
Very well thanks for your advice, I've adapted your method for do coloring like this:

```python
class HighlightCode:

    color_library = []

    def __init__(self, description, regex, color):
        """
        :param description:
        :param regex:
        :param color:
        """
        self.description = description
        self.regex = regex
        self.color = color

        HighlightCode.color_library.append(self)

    @staticmethod
    def highlight(txt):
        """

        :return:
        """
        ret = txt
        for each_definition in HighlightCode.color_library:
            if m := txt.findall(regexp=each_definition.regex):
                for match in m:
                    ret = ret.setColor(ttk.TTkColor.fg(each_definition.color), match=match)

        return ret


HighlightCode('timestamps', r'[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}', '#00AAAA')
HighlightCode('level', 'WARN', '#AAAA00')
HighlightCode('level', 'WARNING', '#AAAA00')
HighlightCode('level', r'\bINFO ', '#44AA00')
HighlightCode('level', 'ERROR ', '#FF8800')
```
And result looks like this:
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/56597585/c86b6226-500d-4a96-b25a-5cb3c6cfd811)

So I'm pleased with this  result, so I think I've sorted this now.
Thank you very much!

**Comment by ceccopierangiolieugenio** [comment]
Great Thanks,
I am curious how it performs with such big files
In this project I made a custom widget to display and highlight big text files 
https://github.com/ceccopierangiolieugenio/tlogg

**Comment by castben** [comment]
Cool I will have a look into, it I'm also courios how did you managed such huge files.

I'm struggling with files > 2MB so I plan to load file by chunks so I can manage let say 500 lines, and scroll up and down loading what ever is required on demand. Loading full file on widget is possible but takes ages to load... I've been working with ttk.TTkTimer to load file in baground and updating a progress bar but is too slow... so I had to implement my own thread to do this job... it is quicker to load file. but still widget struggle when is a lot of text on it.

Thank you for sharing your other project I will have a look into it.
the log reader I'm building is using json parser, and csv to convert some files (that comes from Kibana, and k8s log collectors to an easy readable format...)

**Comment by serverowner2003** [comment]
> Very well thanks for your advice, I've adapted your method for do coloring like this:
> 
> ```python
> class HighlightCode:
> 
>     color_library = []
> 
>     def __init__(self, description, regex, color):
>         """
>         :param description:
>         :param regex:
>         :param color:
>         """
>         self.description = description
>         self.regex = regex
>         self.color = color
> 
>         HighlightCode.color_library.append(self)
> 
>     @staticmethod
>     def highlight(txt):
>         """
> 
>         :return:
>         """
>         ret = txt
>         for each_definition in HighlightCode.color_library:
>             if m := txt.findall(regexp=each_definition.regex):
>                 for match in m:
>                     ret = ret.setColor(ttk.TTkColor.fg(each_definition.color), match=match)
> 
>         return ret
> 
> 
> HighlightCode('timestamps', r'[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}', '#00AAAA')
> HighlightCode('level', 'WARN', '#AAAA00')
> HighlightCode('level', 'WARNING', '#AAAA00')
> HighlightCode('level', r'\bINFO ', '#44AA00')
> HighlightCode('level', 'ERROR ', '#FF8800')
> ```
> 
> And result looks like this: ![image](https://private-user-images.githubusercontent.com/56597585/277965641-c86b6226-500d-4a96-b25a-5cb3c6cfd811.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ1NTA2MTQsIm5iZiI6MTcwNDU1MDMxNCwicGF0aCI6Ii81NjU5NzU4NS8yNzc5NjU2NDEtYzg2YjYyMjYtNTAwZC00YTk2LWIyNWEtNWNiM2M2Y2ZkODExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA2VDE0MTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwOWVkZjM2YzkxYmY4MzIwOWE3ZmVjOTIxM2VjOTM5YzNlOWYwNjNmY2FmNzJlNTMyNDViZGIxMTkwYTY3M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aPbOxMyw98eZuaxXb_rmA03gTtTzbyHcUzKLxKVtPng)
> 
> So I'm pleased with this result, I think I've sorted this now. Thank you very much!

Could you put or complete code to test and use?
