### ISSUE TITLE
How to paste text inside edit line with putty on Windows

### ISSUE THREAD

**Issue by smartkid2003** [ceccopierangiolieugenio/pyTermTk#211]
Hi 
In Putty if the right click then the clipboard is pasted but in pyTermTK the right click doesn't work to paste something. is there any way to do that? paste copied text inside TermTk 
And is it possible to change TermTk in the window title?
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/b8203c5d-6cd7-439b-afa8-8d56b5ba50fc)

**Comment by ceccopierangiolieugenio** [comment]
"ctrl+v" or "ctrl+shift+v" normally supported in any terminal

The
Right click (Putty)
Mid click (any linux environment)
is a built in terminal feature that perform a paste in the app input manager

pyTermTk does not have control over it.
Any terminal app that capture the mouse, automatically disable the terminal "paste on click" feature

You can still handle the Central/Right mouse press and call the built in the clipboard paste

**Comment by ceccopierangiolieugenio** [comment]
Putty seems kind of an oddball:
I managed to paste using:
CTRL+RightClick -> "Paste From CLIPBOARD"
It seems that there is an option to enable CTRL+SHIFT+V
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/0d753e26-cc0a-477d-9e49-3fd84762cc4d)

**Comment by smartkid2003** [comment]
Thanks cool

**Comment by smartkid2003** [comment]
I repeat ctrl+right click and select copy doesn't work in puty. is there any solution for that?

**Comment by ceccopierangiolieugenio** [comment]
I am trying putty under Wine
I can paste using

- CTRL+Ins
- SHIFT+RightMouse
