### ISSUE TITLE
Is it possible to change TermTk on title of terminal window?

### ISSUE THREAD

**Issue by smartkid2024** [ceccopierangiolieugenio/pyTermTk#212]
Is it possible to change TermTk on title of terminal window?
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/692baa14-5a97-4601-8289-8818d250cb61)

**Comment by ceccopierangiolieugenio** [comment]
The terminal title escape sequence is a feature that many terminals supports but not all of them.
You can change it when you initialize the TTk root object:
```python
    root = TTk( title="ABC Title" )
```
i.e.:

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/a2f6c31778347ad1c65858f4ea965ad66ceffe99/ttkDesigner/app/main.py#L38-L45
