### ISSUE TITLE
Copy disabled in new version of ttkDesigner==0.37.0a36

### ISSUE THREAD

**Issue by smartkid2024** [ceccopierangiolieugenio/pyTermTk#221]
Also ctrl+c  Ctrl+Shift+C doesn't work anymore
In Terminal:
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/fb0d756e-ea42-4fe4-9ddc-92620e128937)

Copy disabled in new version of ttkDesigner==0.37.0a36:
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/946b31a3-eec0-4b5d-933d-22fb16aa9107)

**Comment by smartkid2003** [comment]
I tried middle click as you mentioned to copy paste I tried Ctrl+C  Ctrl+Shift+C none of them worked 
And I found out it doesn't work on here:
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/0a577c0b-13ab-418a-8bb7-e6cc37ed8351)

but Ctrl+C works here:
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/93b71b76-090e-43d0-8433-a20791b42ba0)

**Comment by ceccopierangiolieugenio** [comment]
I need to doublecheck the lineedit widget
I suspect that the clipboard support is no more working (or I never implemented it)

**Comment by ceccopierangiolieugenio** [comment]
Yes, the CTRL-C, CTRL-V are not implemented
The SHIFT-CTRL-V should works or the terminal "paste"
I will fix this soon

**Comment by ceccopierangiolieugenio** [comment]
if you upgrade pyTermtk to the version **0.37.0a40** 
`pip3 install --upgrade pyTermTk`
the problem should be fixed
