### ISSUE TITLE
How to set custom event for close icon on window

### ISSUE THREAD

**Issue by smartkid2024** [ceccopierangiolieugenio/pyTermTk#222]
How can I write a custom method for the close icon for example if I press it and then exit from TermTK
self._stop_progress_bar_thread = True
            TTk().quit()

![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/e675d245-bdb8-42cd-a490-5634ab9cfbae)

**Comment by ceccopierangiolieugenio** [comment]
you can just connect the **closed** signal to the **quit** slot
```python
from TermTk import TTk, TTkWindow

root = TTk()

win = TTkWindow(parent=root, pos=(0,0), size=(40,20))
win.closed.connect(root.quit)

root.mainloop()
```

**Comment by smartkid2003** [comment]
I also need to stop the thread i mean self._stop_progress_bar_thread = True does it work with code? and it's my code structure:
```python
class MyCheckLicense(TTkWindow):

    def __init__(self, root):
        self.root = root

 ## Event Methods ##
    pyTTkSlot(str)
    def onCheckBtnClick(self):
        ...
    def onCheckInfoBtnClick(self):
        ...

root = TTk(title="Check License")
root.layout().addWidget(MyCheckLicense(root))
root.mainloop()
```

**Comment by ceccopierangiolieugenio** [comment]
About:
```python
       TTk().quit()
```
You are creating  new root object so you are not quitting the one active.
Use this instead:
```python
        TTkHelper.quit()
```

**Comment by ceccopierangiolieugenio** [comment]
Did you had a look at my example here?
https://github.com/ceccopierangiolieugenio/pyTermTk/issues/213#issuecomment-1887567958
If you use the TTkThread you should not worry about cleaning the thread

**Comment by smartkid2003** [comment]
Yes, I saw but the subject is not only run a timer. It is connected to a server and gets information in the background and it may take time (so the timer is only a simulation)
