### ISSUE TITLE
Save as doesn't change file to the new file in TTk Designer

### ISSUE THREAD

**Issue by smartkid2024** [ceccopierangiolieugenio/pyTermTk#225]
Hi I have opened the file and then saved it as a new file but the opened file doesn't change to the new file that I created by the save as so if I change something to that file it overrides the old one and the main file in  TTk Designer
![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/155442769/b0826b53-adc9-4047-815b-b5116604c127)

Also when I make some changes and open a new file it doesn't ask to save changes and all my changes will be lost

**Comment by ceccopierangiolieugenio** [comment]
yep,
the logic of the saving mechanism and environment is very basic, 
I need to make it more consistent,
I am curious to check if there are some guidelines about consistent uidesign.

**Comment by smartkid2024** [comment]
> yep, the logic of the saving mechanism and environment is very basic, I need to make it more consistent, I am curious to check if there are some guidelines about consistent uidesign.

Also please add undo and redo if it's possible 
Also copy paste or duplicate

**Comment by ceccopierangiolieugenio** [comment]
That's already there (the logic at least),
I am waiting to finish the "Shortcut" feature in order to push all the changes and allow "CTRL+Z" "CTRL+Y" to be used for the undo/redo

**Comment by ceccopierangiolieugenio** [comment]
Starting to implement the undo/redo in #228

**Comment by ceccopierangiolieugenio** [comment]
undo/redo is available in 
**ttkDesigner-0.38.0a0**
I will fix the filename issue soon

**Comment by ceccopierangiolieugenio** [comment]
Filename Issue fixed in
ttkDesigner-0.38.0a2

**Comment by ceccopierangiolieugenio** [comment]
Raised #232 for the ask to save feature
Raised #233 for a widget clipboard (copy/paste) - I feel it can be tricky but I feel that can be implemented with a simple workaround of the undo/redo feature
