### ISSUE TITLE
Missing DataTable

### ISSUE THREAD

**Issue by TheLordOfTheKings** [ceccopierangiolieugenio/pyTermTk#238]
Hi @ceccopierangiolieugenio,
This amazing project misses some vital widgets like advanced DataTable, Switch, and Switchable contents.
It would be awesome to have them, along with ttkDesigner, pyTermTk will be invincible.
But most important is an advanced DataTable.

Thanks in advance.

**Comment by ceccopierangiolieugenio** [comment]
eh...
I always procrastinated the implementation of a proper datatable,
It is going to take a lot of time and effort but I think it is time to start working on it.

About the switch;
you mean this?

![image](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/b211f19b-bb1c-4ec1-9e8b-dfd402d07ada)

it is basically a checkbox,
I think I can easy one to add.

do you have an example of switchable content?

anyway, Thanks.

**Comment by arash88** [comment]
Hey @ceccopierangiolieugenio, Thanks for answering so fast!
After finding the amazing pyTermTk project, I'm really intrigued to start a small TUI application.😄 
With a few more small widgets I can develop all of my GUI needs inside the Terminal and that's mind-blowing!

IMO an advanced DataTable with tree functionalities and inline Buttons (or other widgets) in rows and sorting would be awesome:

![DataTable](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/13942180/bf33c3f2-f616-4fca-bee8-488a72b4dd6c)

Yes, I mean that kind of Toggle/Switch/CheckBox!

As for Switchable containers and some other container widgets that I really like to have, here are some examples, I think all of them are probably already possible in pyTermTk with some little tweaks that I don't know how!)

HidableContainer:
![HidableContent](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/13942180/b46be1f9-f0a0-4197-8cd4-465a28f54ab5)

CollapsibleContainer:
![FoldableContent2-ezgif com-video-to-gif-converter](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/13942180/2f4e38e9-8f1d-49e3-9bb9-d7f2ceec2a34)

SwitchableContainer:
![SwitchableContent-ezgif com-video-to-gif-converter](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/13942180/0b555042-ce32-4901-95d2-c93f37915da6)

Header and Footer:
![header-footer](https://github.com/ceccopierangiolieugenio/pyTermTk/assets/13942180/3596dcee-9f4e-4646-a03b-e111989ea67a)

Thanks.

**Comment by ceccopierangiolieugenio** [comment]
Wow, I totally forgot about this request.
Although, I was sure I already replied it, maybe my answer got lost or never submitted, maybe is Alzheimer, only time will tell.

I am finally starting working on a Table widget,

About header or footer widgets, those can be easily designed using the current layout/widgets/shortcuts.
The reason I haven't implemented anything specific yet is because I still haven't figured out a standard/easy way to do it that does not require piling up a bunch of buttons in a HLayout.
