### ISSUE TITLE
Help with a few questions

### ISSUE THREAD

**Issue by ecliipt** [ceccopierangiolieugenio/pyTermTk#261]
Hey, I've been messing arround with pytermtk again, and I was wondering if the following was possible:
1 - set windows on focus when spawning
2 - get the string id/name of an item of a TTkTree (when recieving a signal such as itemActivated)
3 - kill the terminal shell session when closed (window and tab)
and 4 - get the terminal to run with a command with args on creation (i've seen the program argument in the runShell, but I couldn't manage to get it working with args, ex: "vim test.txt" wont work, and the program just dies.

if any of these aren't possible, it could be some kind of suggestion, idk. Besides that the project is amazing!
Thanks :)

**Comment by ceccopierangiolieugenio** [comment]
1 - To set the window on focus you can just call the [setFocus()](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkWidgets.widget.html#TermTk.TTkWidgets.widget.TTkWidget.setFocus) method of the widget (the window)
Or call the setFocus of the widget inside the window you want to grab the control

2 - It depend on the signal, i.e. itemActivated return the item itself so you already have it.
if you check the FileTree, i extended the widgetItem to include also other fields like 'path'
the itemActivated will return the TTkFileTreeWidgetItem connected.
if you give me an example of what you are trying I can write a sample code.

3 - you can check this example:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/main/tests/t.pty/test.pty.006.terminal.06.py
where I use:

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/30ea762d1bf5d7452d17fe654313260fbb7a859f/tests/t.pty/test.pty.006.terminal.06.py#L87

4 - this one should not be hard, I need to check and maybe implement the proper api to run the custom command

**Comment by ecliipt** [comment]
Thanks for the reply! I'll check the window focus and terminal examples rn. For the 2nd tho, I was planning to make something like the listMenu in your demo, but using a tree so I can make something like a "folder", as I'm using items with no children to spawn windows into my mainFrame. Sorry to bother you with all that tho, there's no need to go into much detail if it's not very convenient. Once again thanks for the support

**Comment by ceccopierangiolieugenio** [comment]
about 4:
> 4 - get the terminal to run with a command with args on creation (i've seen the program argument in the runShell, but I couldn't manage to get it working with args, ex: "vim test.txt" wont work, and the program just dies.

I checked the code and in theory you should be able to run any random command:

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/30ea762d1bf5d7452d17fe654313260fbb7a859f/TermTk/TTkWidgets/TTkTerminal/terminalhelper.py#L57

I made a test in my latest commit that spawn a terminal with "htop" in it

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/d678140cf851fc0243cb5a677ab7152b4b1cefdc/tests/t.pty/test.pty.006.terminal.07.py#L95-L105

**Comment by ecliipt** [comment]
> about 4:
> 
> > 4 - get the terminal to run with a command with args on creation (i've seen the program argument in the runShell, but I couldn't manage to get it working with args, ex: "vim test.txt" wont work, and the program just dies.
> 
> I checked the code and in theory you should be able to run any random command:
> 
> https://github.com/ceccopierangiolieugenio/pyTermTk/blob/30ea762d1bf5d7452d17fe654313260fbb7a859f/TermTk/TTkWidgets/TTkTerminal/terminalhelper.py#L57
> 
> I made a test in my latest commit that spawn a terminal with "htop" in it
> 
> https://github.com/ceccopierangiolieugenio/pyTermTk/blob/d678140cf851fc0243cb5a677ab7152b4b1cefdc/tests/t.pty/test.pty.006.terminal.07.py#L95-L105

yes, i've tried that too and it's works very well, however once you try to use a command with arguments (ex: "htop -t", or the one i said earlier "vim hello.txt") it wont work. The program will just die or, if the terminal is inside a window or anything like it, that same window crashes. I'm not sure if the arguments are handled when parsing the program in ```th.runShell(program="htop -t")```.

**Comment by ceccopierangiolieugenio** [comment]
Yes, I noticed, I will extend the API in the next days in order to include extra params.
Something like:
 th.runShell(["htop", "-h"])

**Comment by ecliipt** [comment]
> Yes, I noticed, I will extend the API in the next days in order to include extra params. Something like:
> 
> ```
> th.runShell(["htop", "-h"])
> ```

Thanks, that would be amazing! And thanks for the hole support overall :)

**Comment by ceccopierangiolieugenio** [comment]
Added In **pytermtk-0.39.0a149**

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/9e70820c72fe4b251f1c8503a1a075f423ad9773/tests/t.pty/test.pty.006.terminal.07.py#L108-L118
