### ISSUE TITLE
Terminal with mouse input

### ISSUE THREAD

**Issue by ecliipt** [ceccopierangiolieugenio/pyTermTk#264]
Hello, sorry to bother again, but I was just wondering if it was possible to listen to mouse inputs in the TTkTerminal?
Thanks

**Comment by ceccopierangiolieugenio** [comment]
well, technically yes, it depend which input you need to listen, 
the mouse events are passed to the tty device but you can extend the ttk terminal to capture and use/modify the input.

**Comment by ecliipt** [comment]
> well, technically yes, it depend which input you need to listen, the mouse events are passed/translated automatically to the tty device but you can extend the ttk terminal to capture and use/modify the input if you need.
> 
> Note, the mouse move event is passed only if the mouse track is enabled in your app
> 
> https://github.com/ceccopierangiolieugenio/pyTermTk/blob/d678140cf851fc0243cb5a677ab7152b4b1cefdc/tests/t.pty/test.pty.006.terminal.07.py#L36

Yeah that makes sence, but i'm trying to use a package that is interactible with the mouse, and when I emulate it in the terminal emulator (inside a ttkwindow) it doesn't seem to listen to the mouse inputs. Are those also passed to the terminal shell itself or just the window?
For example, while trying to use htop inside a terminal inside a ttkwindow, when clicking inside that window in the htop tree elements, it doesn't listen for the mouse inputs, and if i run htop outside of pytermtk (in a normal terminal) it will listen to those inputs and select the item pressed accordingly.
I'm using ```th.runShell(program=["htop"])```.
Thanks

**Comment by ceccopierangiolieugenio** [comment]
Yes, I am able to reproduce the issue with htop, so far only with htop,
if you try vim or the same pyTermTk demo or bpytop, the mouse input works fine.
I need to check which ansi codes are not properly handled.

https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/b54ad555-7a61-4907-8b2f-71c5f784f66a

**Comment by ecliipt** [comment]
> Yes, I am able to reproduce the issue with htop, so far only with htop, if you try vim or the same pyTermTk demo or bpytop, the mouse input works fine. I need to check which ansi codes are not properly handled.
> Peek.2024-06-21.13-37.mp4

Mine doesn't work with any really. If you can, please do check for those code that r not handled.
I'm using a similar code as the examples for the terminal window with the TTkKodeTab (running on a wsl debian). 
Once again, thanks a lot for the support

**Comment by ceccopierangiolieugenio** [comment]
Which system are you using? 
are you working on MAC?

**Comment by ecliipt** [comment]
> Which system are you using? are you working on MAC?

i'm in a windows using wsl debian, so the pytermtk project is running in the wsl debian

**Comment by ceccopierangiolieugenio** [comment]
using a different terminal I am not able to reproduce the issue:

https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/f8ce3ea1-8040-4c94-a9b5-9f2530b4817c

but the issue is still reproducible on xterm.
I managed to install windows on a vm and I tried it,
I can reproduce the issue only on htop, is it the same issue you are facing?

https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/c50624c6-2051-4712-b195-1feb6a4e5b2d

**Comment by ceccopierangiolieugenio** [comment]
using a different terminal I am not able to reproduce the issue:

https://github.com/ceccopierangiolieugenio/pyTermTk/assets/8876552/f8ce3ea1-8040-4c94-a9b5-9f2530b4817c

but the issue is still reproducible on xterm.
I managed to install windows on a vm and I tried

**Comment by ceccopierangiolieugenio** [comment]
The issue is related to this escape command,
basically is a combination of 2 different codes
```
'<ESC>[?1006;1000h'
```
I was not aware about this syntax:
I will fix it soon.

**Comment by ceccopierangiolieugenio** [comment]
the fix is available in 
**pytermtk-0.39.0a154**
