### ISSUE TITLE
Default sorting for a column on a  TTkTree()

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#275]
Hi
 This  is most a question rather than a problem.

 I've a TTkTree() object I'm using to hold information; my view has several columns to show, what I was wondering is, it is  there any  method I can use to sort information on tree as soon as it is shown? instead of clicking at top header to sort this column?

Like  setting  up a "default" sorting.

**Comment by ceccopierangiolieugenio** [comment]
Yes, but I forgot to expose the function
you can try this workaround, I will fix it in the next release:
```python
tree._treeView.sortItems(colNumber, TTkK.SortOrder.AscendingOrder)
```
in the future will simply be:
```python
tree.sortItems(colNumber, TTkK.SortOrder.AscendingOrder)
```
anyway, I with the TTkTable release I am planning to improve the tree widget documentation as well.
