### ISSUE TITLE
Support for gpm?

### ISSUE THREAD

**Issue by hexanitrohexaazaisowurtzitane** [ceccopierangiolieugenio/pyTermTk#295]
I've been trying to use pytermtk in a barebones instalation of debian and i'm currently using gpm as a mouse cursor, does pytermtk support it or anything alike? I tried to run the demo script and it didn't seem to at least, am I missing something? Thanks

**Comment by ceccopierangiolieugenio** [comment]
pyTermTk use the generic ansi code sent by the terminal, it should be independent by the mouse driver.
do you know if your terminal supports the mouse input (i.e. using vim),
so far I tested with multiple terminals, mainly xterm and terminator.
have you tried some other terminal?
which one are you using?

**Comment by hexanitrohexaazaisowurtzitane** [comment]
I was working on hyper x with the debian12 yesterday, and it did support mouse, therefore the usage of gpm. I works both on vim and htop so that's what made me curious ab why it didn't work with pytermtk
I tried looking around but didn't find much, so I switched to wsl and it works perfectly.
I apologize for the trouble and thanks for the support

**Comment by ceccopierangiolieugenio** [comment]
Here it is, It took some time dealing with a pure ctypes driver implementation, but it is slowly coming through

https://github.com/user-attachments/assets/6ffb5879-acd5-4635-98d9-5e41b4d8dc13

**Comment by ceccopierangiolieugenio** [comment]
Added GPM support in:

https://ceccopierangiolieugenio.github.io/pyTermTk-Docs/info/resources/experimental.html#gpm-integration
