### ISSUE TITLE
Request: text wrap feature

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#30]
I can't find anything in the source or the docs that discusses text wrapping if text is wider than the widget on which it is displayed. I would like to have this option, if possible. And it would be even better if he user could specify the wrap column number, in case they want to wrap at a different boundary than the widget width. Thank you for your consideration!

**Comment by ceccopierangiolieugenio** [comment]
The wrap feature is not implemented yet, It is a bit tricky because it could slow down the update for big files and I still have not found an optimal way to implement it.
but I think I will work on it soon after I add the TABS support in the edit mode (right now only are only displayed correctly but if you try to edit it the cursor position is not correctly aligned)

**Comment by jeffwright13** [comment]
I can probably work around it for now using the [textwrap](https://docs.python.org/3/library/textwrap.html) module.

**Comment by ceccopierangiolieugenio** [comment]
I am starting to implement the "Wrap feature"  inside the branch [TTkTextEdit_Wrap](https://github.com/ceccopierangiolieugenio/pyTermTk/tree/TTkTextEdit_Wrap)
You can try the first commit:
https://github.com/ceccopierangiolieugenio/pyTermTk/commit/6bb645b44a0db59672fc2dde9ea591f69e097d19

I added a fixed wrap example in the textedit showcase:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/9ef1bb1d8897be6d89838a4f683c00b9b9bff472/demo/showcase/textedit.py#L73-L78

both fixed width and widget width are working
```
    te.setLineWrapMode(ttk.TTkK.WidgetWidth)
```

```
    te.setLineWrapMode(ttk.TTkK.FixedWidth)
    te.setWrapWidth(40)
```

**Comment by ceccopierangiolieugenio** [comment]
Text wrap feature deployed in 
pyTermTk [0.9.0a23](https://pypi.org/project/pyTermTk/0.9.0a23/)
