### ISSUE TITLE
Dead links on Layouts page

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#33]
The [layouts page](https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkLayouts.html) has a couple of issues:
1) All three of the tutorials (Box, Grid, Default Layout) reference the same URL: https://github.com/ceccopierangiolieugenio/pyTermTk/blob/main/tutorial/002-layout.md.
2) That link is actually dead (404 response)

**Comment by ceccopierangiolieugenio** [comment]
Fixed in https://github.com/ceccopierangiolieugenio/pyTermTk/commit/a74acdca4df3790e9ae36dffe859b493e74939ed
The layout page has been updated:
https://ceccopierangiolieugenio.github.io/pyTermTk/autogen.TermTk/TermTk.TTkLayouts.html
