### ISSUE TITLE
Suggestions for how to dynamically show/hide a text area when a line is clicked

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#38]
Was wondering if you might have some suggestions on how to show/hide a text area (like TTkTextEdit widget) when a `TTkList` `textClicked` event occurs. I've managed to create a callback for a `textClicked` event which populates a `TTkLogViewer` widget, but ideally what I would like to be able to do is click the `TTkList` list element, and have a TextEdit widget pop up next to it (or under it) to show some text; and then when the list element is clicked again, to hide the TextEdit widget.

Basic idea like the third example movie [here](https://github.com/jeffwright13/pytest-fold).

I hope this is clear what I am trying to do... :-)

**Comment by ceccopierangiolieugenio** [comment]
I think a Tree may help you,
or a series of Buttons stacked vertically with a TextEdit in between them that will change visibility if the button in pressed (this one would be very similar to the third example)
or a custom widget would perfectly works (this is quite a simple task)
you just need to choose the way you want the results to be displayed.
if you like the third example I can easily provide you a custom widget,
you just need to decide the format of the data input.

**Comment by jeffwright13** [comment]
Actually, I really like the tabbed layout I have in place now (that's the first example on my site; I will update the video to show the latest). The tabs make it easy to organize the results into categories. So there's a Summary tab, a Pass tab, a Fail tab, etc. On each tab I have a Label widget which is the width of the full screen, and on that label I put a Tree widget. 
At this point I have it so that I can list the result titles in trees, but I haven't yet figured out how to then show the result details once the title is clicked.

Is the visibility attribute part of the base Widget class? So that I can do something like:
```
@ttk.pyTTkSlot(ttk.TTkWidget)
def callback(item: ttk.TTkWidget) -> None:
    item._visible = False
    sleep(3)
    item._visible = True
```

**Comment by ceccopierangiolieugenio** [comment]
The visibility is addressed using the "**hide**" "**show**" methods as in the demo:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/main/demo/demo.py#L212-L215

**Comment by jeffwright13** [comment]
Because of the length of my screen recording I had to make the gif super small. The original file (.mov) is about 35MB and is located [here](https://drive.google.com/file/d/1e0o78QICr43ZXPYyKL6QsVFEbzVEV17s/view?usp=sharing).

**Comment by jeffwright13** [comment]
Closing, per contributed code in [pytest-tui](https://pypi.org/project/pytest-tui/) v 0.9.0.
