### ISSUE TITLE
demo/gittk.py doesn't work (but I fixed it)

### ISSUE THREAD

**Issue by jeffwright13** [ceccopierangiolieugenio/pyTermTk#41]
This demo (`python gittk.py`) doesn't run correctly due to two errors:

1) The call to `git.Repo` is made with `.` as its argument, so if you are in a subdirectory of the repo (like, in the `/demo` folder), it fails. Fix is to add `search_parent_directories` to Line 38:

`repo = git.Repo('.', search_parent_directories=True)`

2) Line 97 has syntax errors, and should be:

`diffText.setText(line)`

AFter making those changes, it seems to work.

**Comment by ceccopierangiolieugenio** [comment]
I haven't adapted gittk to the reworked TTkTextEdit and TTkString.
Fix delivered in: https://github.com/ceccopierangiolieugenio/pyTermTk/commit/e19e3add7192f905b1858e8a3b57b859a12d0bb9
