### ISSUE TITLE
Only for unix?

### ISSUE THREAD

**Issue by borrrden** [ceccopierangiolieugenio/pyTermTk#42]
This isn't listed anywhere in the limitations but is this project meant only for unix systems?  Windows immediately produces the following error in Windows Terminal:

> ERROR: No module named 'termios'

**Comment by borrrden** [comment]
It's not a problem, just something I think is worth pointing out in the README.

**Comment by ceccopierangiolieugenio** [comment]
I will add this info in the README.
Thanks.

**Comment by ceccopierangiolieugenio** [comment]
MS Windows support added in:
**v0.36.0-a**
