### ISSUE TITLE
Wanted to check with you this... shouldn't be `TTkComboBox` here?

### ISSUE THREAD

**Issue by castben** [ceccopierangiolieugenio/pyTermTk#60]
At the reference below, I suppose this will give the default name to the widget if you do not explicitly add it 

https://github.com/ceccopierangiolieugenio/pyTermTk/blob/de5bbac1f91c5f89db771d4354bb21f049deacd7/TermTk/TTkWidgets/combobox.py#L46

But I will expect to be a TTkComboBox... I know this is a minor issue but just wondering about it.
![image](https://user-images.githubusercontent.com/56597585/194840491-80340b89-5deb-43fb-bc52-fbbd1891f780.png)

**Comment by ceccopierangiolieugenio** [comment]
yes I need to fix this.
the reason of **_name** was for debugging purposes but I rarely used it,
I wanted to find a more elegant way to address the name of the object but I was too lazy to find a better way to identify the object.
I will fix this typo soon.
Which debugger are you using? I like it.

**Comment by ceccopierangiolieugenio** [comment]
Fixed in: https://github.com/ceccopierangiolieugenio/pyTermTk/commit/ac51650c883e47528a37bf34b6069c95b0cbc5fc

**Comment by castben** [comment]
Ah cool, 
Actually I've used this feature to locate widgets on a form to gather their actual values set, as some of my widgets need to re-populate their vakues depending on other widgets values...

I'm using IntellJ but it is a nightmare to do debugging, as I need to launch my program apart in a real Terminal, then attach debugger from IntellJ to my program running on this terminal...

It is not perfect as you lose total control of the window (it seems to freeze) only way I've found to trigger some events is:

1) Open actual form I want to debug
2) move to actual widget I need (using tab)
3) Attach debug process from intelliJ, then all freezes on my pyTermTk program
4) Use ^J to trigger event I want from this widget...
5) IntelliJ then stop at the "break" point I want...

as you see it is a very cumbersome process... if you have any other way to debug I will highly appreciate it 

Terminal window embbed into IntelliJ Do not support programs that are using libraries like ncurses/curses...

Regards,

**Comment by ceccopierangiolieugenio** [comment]
I find vscode very handy to debuf python code and it can display i easily in the builtin terminal
![image](https://user-images.githubusercontent.com/8876552/194878342-9c4f1e9a-fcf8-46b5-bb0d-1d3d8d3812e6.png)

**Comment by castben** [comment]
That's look pretty cool!

I wonder if that will work with me... as I'm on Linux I think I saw some VScode running on linux I may try it

Thank you very much. I think you can proceed to close this issue too :+1:
