### ISSUE TITLE
String len() is used as width

### ISSUE THREAD

**Issue by luchr** [ceccopierangiolieugenio/pyTermTk#67]
# Description of the problem

Looking at the code I see many lines where the `len()` of a string is used for the (terminal-)width of this string. But there are codepoints with width 0 and 2. For example "o" with an arrow above: o⃗ (U+006F U+20D7). The U+20D7 arrow has width 0. Or 😼 (U+1f63c): this codepoint has width 2. If one enters or uses such codepoints the whole layout is "out of sync".

## Example

Here is an example with `demo.py` and the form widgets: Before:
![20221122_210446](https://user-images.githubusercontent.com/7441996/203412140-e42b536c-fc7e-46eb-bfcf-634b4c6bd918.png)
and after:
![20221122_210526](https://user-images.githubusercontent.com/7441996/203412175-debb898d-c373-479f-90ec-3633c95c21fd.png)

## Question

Are there any plans to support `wcwidth`?

**Comment by zerowhybr** [comment]
I am also experiencing this problem with ANSI color codes. I believe the library is considering color sequences as part of terminal length.
Maybe this can be helpful for fixing this issue, it is a fix that another project used for this very same problem: [Tabulate source code](https://github.com/astanin/python-tabulate/blob/83fd4fb98926c8a6fdf45caa1b91ee8913b64dcb/tabulate/__init__.py#L996)

**Comment by ceccopierangiolieugenio** [comment]
I was planning to find a proper way to handle fiull/halfwidth characters and I still haven't found a solution,
I will check soon how can I integrate wcwidth.

**Comment by luchr** [comment]
I've written some thoughts and some links (e.g. how others have tried to solve this), here: [luchr/WidthInTerminals](https://github.com/luchr/WidthInTerminals)

**Comment by ceccopierangiolieugenio** [comment]
Still some work to do but it is shaping up:
[Peek 2022-12-01 23-33.webm](https://user-images.githubusercontent.com/8876552/205183222-ff89c456-a57f-4946-b39c-7d5eca59c728.webm)

**Comment by ceccopierangiolieugenio** [comment]
WIP
![image](https://user-images.githubusercontent.com/8876552/205523430-d3d0a829-c67e-4e82-9d53-f88ccf4d0b23.png)

**Comment by ceccopierangiolieugenio** [comment]
The fix should be implemented in b2d4266
There is not yet any support for "Zero Width Joiner" because I noticed that the terminals I am using are not resolving it.

**Comment by luchr** [comment]
Thanks for your effort.

The ZWJ is supported e.g. by [kitty](https://github.com/kovidgoyal/kitty/).

The Unicode varselectors `FE0F` and `FE0E` are supported by many terminals:

For a test:
```
# printf '\u231a\n\u231a\ufe0e\n\u231a\ufe0f\n'
⌚
⌚︎
⌚️
# printf '\u2764\n\u2764\ufe0e\n\u2764\ufe0f\n'
❤
❤︎
❤️
```

**Comment by ceccopierangiolieugenio** [comment]
The varselectors seems to work,
Just noticed a glitch if mixed with fullsize chars, I will check it soon.

[Peek 2022-12-07 10-27.webm](https://user-images.githubusercontent.com/8876552/206154773-172ed68c-663f-4472-b4a4-f263e09ab5ec.webm)

**Comment by luchr** [comment]
Perhaps this glitch has something to do with
```python
import TermTk
str1 = TermTk.TTkString("\u2764\ufe0f")
print("--\n", str1, "\n", str1.termWidth(), sep='')
```
which gives a `termWidth` of 1 (but 2 columns are used):
```
--
❤️
1
```

**Comment by ceccopierangiolieugenio** [comment]
I think the hearth is 1 column wide.
you can see how my terminal (terminator) display it it, it doesn't shift the next char.
![image](https://user-images.githubusercontent.com/8876552/206218382-e36b0a8c-1b41-47bf-be7a-d856c2a049cd.png)
I need to refine the way the zero chars are used in my terminal "rasterizer" routine when a window edge is covering the rightmost part of it.

**Comment by ceccopierangiolieugenio** [comment]
Better:

[Peek 2022-12-07 15-51.webm](https://user-images.githubusercontent.com/8876552/206226435-d3cc4d71-cf1b-4e1e-89c7-080c73f6234a.webm)

**Comment by luchr** [comment]
I think all of the VTE-based terminals handle the `FE0F` var selector for producing 2 columns (rendering) and are moving the cursor only 1 column (because they use some `wcwidth` idea, instead of `wcswidth` or getting the width for EGCs). Other terminals (like kitty or contour) show 2 columns and move the cursor two columns.
![20221207_164706](https://user-images.githubusercontent.com/7441996/206225314-f2515db5-e925-4923-9769-2966100c285d.png)
![20221207_164711](https://user-images.githubusercontent.com/7441996/206225338-2de25a69-7107-406f-b600-d1c6b80d5649.png)

Here is a long discussion (about getting a "standard"): https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/9

**Comment by luchr** [comment]
Vim is (in this context) not suitable (as width test, etc.) because for an editor there are other requirements than for a terminal emulator. Fun fact: Vim can render some(!) combining characters correctly because of this [patch](https://github.com/vim/vim/commit/7e2ec008f5c5152205d0b8a7d88177b374225d8d) from me :-)

Until the terminal persons reach some "consensus" how to handle ZWJ and Var-Selectors etc. and adapt their terminal emulators, I think your "size of char test" is an acceptable approximation (and fast because no ECG-segmentation is performed).
[The other option "to program for all the different terminal emulator behaviours and/or place the cursor explicitly after every ZWJ and Var-Selectors" is toooo much work.]

So let's close, or?
