### ISSUE TITLE
[Question]use mouse to select texts

### ISSUE THREAD

**Issue by NickyXu1989** [ceccopierangiolieugenio/pyTermTk#69]
Hello, great thanks for your efforts in this project. I have got a question as below.
Is there some way I can use to interrupt mouse monitoring so that I can select texts from the interface and do some copy action?
Thanks a lot.

**Comment by ceccopierangiolieugenio** [comment]
Thanks a lot for your comment.

About the mouse enable/disable feature,
I haven't thought a proper api yet.
I probably need to implement something like:
`root.mouseOn()`
`root.mouseOff()`

But, you can still use:
`ttk.TTkTerm.push(ttk.TTkTerm.Mouse.ON)`
`ttk.TTkTerm.push(ttk.TTkTerm.Mouse.OFF)`
to enable/disable the mouse capture

I added an example here:
https://gist.github.com/ceccopierangiolieugenio/f6b07053104ec38a3728d5b6edff3d59

You can [try it online here](https://ceccopierangiolieugenio.github.io/pyTermTk/sandbox/sandbox.html?fileUri=https://gist.githubusercontent.com/ceccopierangiolieugenio/f6b07053104ec38a3728d5b6edff3d59/raw/c8de52bdbc08c8348b74b152c6955773331e86b5/issue_69_DisableMouse.py)

**Comment by ceccopierangiolieugenio** [comment]
I added it in the [Sandbox](https://ceccopierangiolieugenio.github.io/pyTermTk/sandbox/sandbox.html) demo

![image](https://user-images.githubusercontent.com/8876552/206260205-d6162b8a-8186-4c90-898d-09699dc2eac0.png)

**Comment by NickyXu1989** [comment]
Great thanks for your quick response. The problem is solved.
