### ISSUE TITLE
[Question] table view can not scroll horizontally

### ISSUE THREAD

**Issue by NickyXu1989** [ceccopierangiolieugenio/pyTermTk#79]
Hello there,
These days, I'm using table view to show some information. There is one column coming with a very long str, and I have no idea how to make the horizontal scroll bar work. Would you please help to show me a demo about the table view with the horizontal scroll bar?
Great Thanks.

**Comment by ceccopierangiolieugenio** [comment]
The actual table  (fancyTable) was a prototype and I was planning (as it happened for the tree widget) to rewrite it to make it more close to the QT api/usability.
Anyway, I can easily add a horizontal scrollbar, I can do it in the next release.

**Comment by ceccopierangiolieugenio** [comment]
Fix added in: https://github.com/ceccopierangiolieugenio/pyTermTk/commit/f14821d7d1954c217a0520b7cea5174908739dbb

[Peek 2022-12-18 16-03.webm](https://user-images.githubusercontent.com/8876552/208307888-2c2b6019-0268-41ad-897c-5d9245a0651f.webm)

**Comment by NickyXu1989** [comment]
I use a scrollarea outside the table, it work quite ok. Looking forward to your new release.

**Comment by ceccopierangiolieugenio** [comment]
Deployed in [0.14.0](https://pypi.org/project/pyTermTk/)

[sandbox](https://ceccopierangiolieugenio.github.io/pyTermTk/sandbox/sandbox.html)
