### ISSUE TITLE
Close Window Button

### ISSUE THREAD

**Issue by nickandwolf** [ceccopierangiolieugenio/pyTermTk#81]
Hello again! I managed to make a little X button on a window but I do not know how to call the window close function when the X is clicked. I can make the X go away but not the window itself.

**Comment by ceccopierangiolieugenio** [comment]
You can check this as example:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/8f4d088f23382dcff4756121285277f5e7d02ba7/TermTk/TTkWidgets/tabwidget.py#L68-L70
where you can connect the clicked button with the "window.close"
Anyway, I was thinking to implement the window close button for a very long time, if you need it, I can add this in the next release

**Comment by nickandwolf** [comment]
I would love a close window button. And an option for minimize (drops the window to just a title. potentially could set it to go to a pre-made anchor point when minimized)

**Comment by ceccopierangiolieugenio** [comment]
The close button is quite easy to be implemented,
the minimize button that just reduce the window to a simple title label is doable.
Minimizing to an anchor point is something I have to think about, also a taskbar could be implemented

**Comment by ceccopierangiolieugenio** [comment]
Added the window close button in: https://github.com/ceccopierangiolieugenio/pyTermTk/pull/84/commits/fbe8657b0528eea749579a32f2abf3990762ad41

You can ebale it with:
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/fbe8657b0528eea749579a32f2abf3990762ad41/demo/showcase/windows.py#L39

I am planning to add also the min/max button and menuwindow

**Comment by ceccopierangiolieugenio** [comment]
I am trying to prototype those buttins:

[Peek 2022-12-18 22-42.webm](https://user-images.githubusercontent.com/8876552/208323161-67b551aa-afab-4145-ad9a-c130ac3f153b.webm)

Any suggestion is well accepted

**Comment by ceccopierangiolieugenio** [comment]
Winalised the windows controls,
I will push the changes soon:

[Peek 2022-12-20 00-01.webm](https://user-images.githubusercontent.com/8876552/208551154-8d7e67f8-5443-419b-9b30-1ab1dbd719e2.webm)
