### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by nickandwolf** [ceccopierangiolieugenio/pyTermTk#92]
Hello again! I am trying to tie a scrollbar to a frame but cannot seem to find clear examples or documentation. I just need a vertical bar.

Thank you!

**Comment by ceccopierangiolieugenio** [comment]
if you need a scrollbar you may try to use a scroll area
https://github.com/ceccopierangiolieugenio/pyTermTk/blob/main/demo/showcase/scrollarea.py
the scrollbar is just a widget that trigger some signals anytime its value change,
it is up to the widget to refresh and scroll its content.
If you tell me your end result I can try to make a demo.

**Comment by nickandwolf** [comment]
I would like to make a frame that holds information and scrolls vertically.
I also need to put a scrollbar on the side of my terminal to scroll up and down.

Like this window on this website. We can scroll the whole page up and down and then this little comment box needs to scroll too.

**Comment by nickandwolf** [comment]
Okay I got scrollarea to work. That viewport() really got me. Thank you :D

**Comment by nickandwolf** [comment]
Is there a way for me to turn off the horizontal scroll bar?
I've tried:
`root.setHorizontalScrollBarPolicy(ttk.TTkK.ScrollBarAlwaysOff)`
`root = ttk.TTkScrollArea(parent=root1, horizontalScrollBarPolicy = ttk.TTkK.ScrollBarAlwaysOff, size=(84, 30), pos=(0, 0))`
`root._horizontalScrollBar.hide()`
`root.setHorizontalScrollBarPolicy(ttk.TTkK.ScrollBarAlwaysOff)`

**Comment by ceccopierangiolieugenio** [comment]
Justg noticed that you can only set the policy using the setter and not the constructor:
```
root.setHorizontalScrollBarPolicy(ttk.TTkK.ScrollBarAlwaysOff)
```
I will add the constructor in the next commit
